/**
 * Suggestion catalogues for the master / per-event profile.
 *
 * Industry: a flat list — used in a `<datalist>` so the user can pick
 * one or type a custom value.
 * Interests: grouped by category and rendered as a chip selector with
 * search + add-custom support (see InterestPicker).
 */

export const INDUSTRY_OPTIONS: string[] = [
  // Tech / digital
  'Technology',
  'Software',
  'AI / Machine Learning',
  'Data Science',
  'Cybersecurity',
  'Crypto / Web3',
  'Telecom',
  // Product / design
  'Product',
  'Design',
  'UX / UI',
  // Marketing / growth
  'Marketing',
  'Advertising',
  'Public Relations',
  'Analytics',
  // Finance / legal
  'Finance',
  'Banking',
  'Investing',
  'Venture Capital',
  'Insurance',
  'Accounting',
  'Law / Legal',
  'Compliance',
  // Business
  'Consulting',
  'Strategy',
  'Sales',
  'HR / Recruiting',
  // Industries
  'Healthcare',
  'Pharma',
  'Biotech',
  'Education',
  'Research',
  'Manufacturing',
  'Construction',
  'Real Estate',
  'Architecture',
  'Retail',
  'E-commerce',
  'Hospitality',
  'Tourism',
  'Food & Beverage',
  'Automotive',
  'Aerospace',
  'Defense',
  'Transportation',
  'Logistics',
  'Energy',
  'Sustainability',
  'Climate Tech',
  'Agriculture',
  // Media / creative
  'Media',
  'Journalism',
  'Publishing',
  'Entertainment',
  'Gaming',
  'Music',
  'Film',
  'Fashion',
  'Beauty',
  // Public / social
  'Government',
  'NGO / Nonprofit',
  'Public Sector',
  // Lifestyle
  'Sports',
  'Fitness',
  'Other',
];

export const INTEREST_CATALOG: Record<string, string[]> = {
  'Tech & Engineering': [
    'Software Engineering',
    'Backend Development',
    'Frontend Development',
    'Mobile Development',
    'iOS',
    'Android',
    'Cloud Computing',
    'DevOps',
    'Distributed Systems',
    'Cybersecurity',
    'Web3 / Blockchain',
    'Hardware',
    'Robotics',
    'IoT',
    'Open Source',
  ],
  'AI & Data': [
    'AI & Machine Learning',
    'LLMs',
    'Computer Vision',
    'NLP',
    'Data Science',
    'Data Engineering',
    'Analytics',
    'Causal Inference',
    'AI Safety',
    'Interpretability',
  ],
  'Product & Design': [
    'Product Management',
    'Product Strategy',
    'UX Design',
    'UI Design',
    'Design Systems',
    'User Research',
    'Prototyping',
    'Accessibility',
    'Brand Identity',
    'Illustration',
    'Type & Typography',
  ],
  'Business & Strategy': [
    'Strategy',
    'Operations',
    'Sales',
    'Business Development',
    'Consulting',
    'Project Management',
  ],
  'Startup & Investing': [
    'Startups',
    'Founders',
    'Fundraising',
    'Venture Capital',
    'Angel Investing',
    'B2B SaaS',
    'Indie Hacking',
  ],
  'Marketing & Growth': [
    'Marketing',
    'Product Marketing',
    'Growth',
    'SEO',
    'Content',
    'Brand',
    'Storytelling',
    'Public Relations',
    'Social Media',
    'Launches',
  ],
  'Leadership & People': [
    'Leadership',
    'Engineering Leadership',
    'Management',
    'Mentorship',
    'Coaching',
    'Hiring',
    'People Operations',
    'Public Speaking',
  ],
  'Finance & Legal': [
    'Finance',
    'Investing',
    'Markets',
    'Accounting',
    'Law',
    'Compliance',
  ],
  'Health & Wellness': [
    'Health Tech',
    'Wearables',
    'Sleep Science',
    'Behavioral Change',
    'Fitness',
    'Mental Health',
    'Nutrition',
  ],
  'Creative & Lifestyle': [
    'Music',
    'Film',
    'Photography',
    'Writing',
    'Art',
    'Architecture',
    'Travel',
    'Fashion',
    'Food',
  ],
  'Other': [
    'Education',
    'Research',
    'Sustainability',
    'Diversity & Inclusion',
    'Career growth',
    'Reading Papers',
    'Workshops',
  ],
};

export function getAllCatalogInterests(): string[] {
  return Object.values(INTEREST_CATALOG).flat();
}
